apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-refresh-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-refresh-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-refresh-controller
subjects:
- kind: ServiceAccount
  name: pod-refresh-controller
roleRef:
  kind: Role
  name: pod-refresh-controller
