linters:
  enable-all: true
  disable:
  - exhaustruct
  - nlreturn
  - tenv

linters-settings:
  depguard:
    rules:
      main:
        allow:
        - "$gostd"
        - "github.com/hashfunc/pod-refresh-controller"
        - "k8s.io"
        - "github.com/samber"

  gci:
    sections:
    - standard
    - default
    - prefix(github.com/hashfunc/pod-refresh-controller)

  gofumpt:
    module-path: "github.com/hashfunc/pod-refresh-controller"
